"""empty message

Revision ID: 42f3492ca5c5
Revises: 9845a28fc8e9
Create Date: 2025-09-03 08:22:58.494073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42f3492ca5c5'
down_revision = '9845a28fc8e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gcal_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('gcal_updated', sa.DateTime(), nullable=True))
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=200),
               existing_nullable=False)
        batch_op.alter_column('notes',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.drop_index('ix_event_user_id')

    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('due_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('completed', sa.Boolean(), nullable=False))
        batch_op.drop_index('ix_task_user_id')
        batch_op.drop_column('date')
        batch_op.drop_column('done')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('google_email', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('google_refresh_token', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('google_calendar_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('google_sync_token', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('google_channel_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('google_resource_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('google_channel_expire', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('google_channel_expire')
        batch_op.drop_column('google_resource_id')
        batch_op.drop_column('google_channel_id')
        batch_op.drop_column('google_sync_token')
        batch_op.drop_column('google_calendar_id')
        batch_op.drop_column('google_refresh_token')
        batch_op.drop_column('google_email')

    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('done', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('date', sa.DATE(), autoincrement=False, nullable=True))
        batch_op.create_index('ix_task_user_id', ['user_id'], unique=False)
        batch_op.drop_column('completed')
        batch_op.drop_column('due_date')

    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.create_index('ix_event_user_id', ['user_id'], unique=False)
        batch_op.alter_column('notes',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
        batch_op.alter_column('title',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=150),
               existing_nullable=False)
        batch_op.drop_column('gcal_updated')
        batch_op.drop_column('gcal_id')

    # ### end Alembic commands ###
